/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meh.fun.Problems_1_10;

import java.util.List;
import meh.fun.Problem_Utilities.FibonacciGenerator;
import meh.fun.Problem_Utilities.GenerationException;
import meh.fun.Problem_Utilities.GenerationType;

/**
 *
 * @author n439081
 */
public class problem2 {

  /**
   * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
   */
  public static void main(String[] args) throws GenerationException {
    
    FibonacciGenerator gen = new FibonacciGenerator(4000000,GenerationType.LIMIT);
    
    List<Long> fibNums = gen.getFibonacciNumbers();
    
    int result = 0;
    
    for(long fibNum: fibNums){
      if( fibNum%2 == 0 ) result += fibNum;
    }
    
    System.out.println(result);
  }
  
}
